apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: mlops
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: mlops_diabetes

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: mlops
data:
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW_DB: airflow_db
  AIRFLOW_ADMIN_EMAIL: admin@example.com
  SOURCE_DATA_PATH: /opt/airflow/data/diabetic_data.csv
  BATCH_SIZE: "15000"
  TARGET_COLUMN: readmitted

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: mlops
data:
  API_HOST: "0.0.0.0"
  API_PORT: "8000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlit-config
  namespace: mlops
data:
  API_BASE_URL: http://api:8000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config
  namespace: mlops
data:
  LOCUST_HOST: http://api:8000